services:
  generator_unit:
    image: "alisafapour/news-aggregator-generator-unit"
    depends_on:
      - rabbit_mq
      - mongo_db
    restart: on-failure
  fetch_unit:
    image: "alisafapour/news-aggregator-fetch-unit"
    depends_on:
      - rabbit_mq
      - mongo_db
      - generator_unit
    restart: on-failure
  save_unit:
    image: "alisafapour/news-aggregator-xml-save-unit"
    depends_on:
      - rabbit_mq
      - mongo_db
      - generator_unit
      - fetch_unit
    restart: on-failure
  rabbit_mq:
    image: "rabbitmq:management"
    ports:
      - "18010:15672"
      - "18009:5672"
  mongo_db:
    image: "mongo:latest"
    ports:
      - "28101:27017"