services:
  generator_unit:
    build:
      context: ./URL Generator Unit
    depends_on:
      - rabbit_mq
      - postgres_db
    restart: on-failure
  fetch_unit:
    build:
      context: ./URL Fetch Unit
    depends_on:
      - rabbit_mq
      - generator_unit
    restart: on-failure
  save_unit:
    build:
      context: ./XML Save Unit
    depends_on:
      - rabbit_mq
      - mongo_db
      - fetch_unit
    restart: on-failure
  rabbit_mq:
    image: "rabbitmq:management"
    ports:
      - "18010:15672"
      - "18009:5672"
    restart: on-failure
  mongo_db:
    image: "mongo:latest"
    ports:
      - "28101:27017"
    restart: on-failure
  postgres_db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: on-failure