services:
  generator_unit:
    build:
      context: ./URL Generator Unit
    networks:
      - nag-net
    depends_on:
      - rabbit_mq
      - postgres_db
    restart: on-failure
  fetch_unit:
    build:
      context: ./URL Fetch Unit
    depends_on:
      - rabbit_mq
      - generator_unit
    restart: on-failure
    networks:
      - nag-net
  save_unit:
    build:
      context: ./XML Save Unit
    depends_on:
      - rabbit_mq
      - mongo_db
      - fetch_unit
    restart: on-failure
    networks:
      - nag-net
  rabbit_mq:
    image: "rabbitmq:management"
    ports:
      - "18010:15672"
    restart: on-failure
    networks:
      - nag-net
  mongo_db:
    image: "mongo:latest"
    restart: on-failure
    ports:
      - "28017:27017"
    networks:
      - nag-net
  postgres_db:
    image: "postgres:latest"
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=1234
    networks:
      - nag-net
networks:
  nag-net: